layout_spectrum: 0.0539376
typography_spectrum: 0.2202592
color:
  saturation: 0.6387905
  lightness: 0.4358556
  brandStrength: 0.9160696
  rhythmicContrast: 0.168891
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: I made this on the subway
